name: Deploy to GHCR

on:
  push:

jobs:
  deploy-to-ghcr:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Build
        shell: bash
        run: |
          mkdir releases
          mkdir ./dist/
          touch mutagen-agents.tar.gz
          cp mutagen-agents.tar.gz ./dist/
          ls ./dist/
