name: Test

on:
  push:
    branches:
      - main
      - master
    paths:
      - '**'

  workflow_dispatch:

jobs:
  build:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      # Set required environment variables
      - run: |
          BASE_BRANCH=${GITHUB_REF#refs/heads/}
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV
        shell: bash

      # Set required environment variables
      - run: |
          echo $BASE_BRANCH
        shell: bash