name: Test

on:
  push:
    branches:
      - main
      - master
    paths:
      - '**'

  workflow_dispatch:

jobs:
  balena_cloud_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: balena-io/deploy-to-balena-action@Remove-versionbot-reference-from-the-README
        id: build
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: maggie0002/test-fleet
  