name: Deploy to GHCR

on:
  push:
    tags:
      - "*.*.*"

jobs:
  deploy-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update balena.yml
        uses: balena-io-experimental/balena.yml-action@yq
        with:
          # Synchronise the GitHub README with the Balena Hub README
          sync_readme: true
          sync_tag: true

      - run: cat balena.yml
